version: '3'
services:
  openvidu-dev:
    image: openvidu/openvidu-dev:2.25.0
    ports:
     - 4443:4443
    environment:
     - OPENVIDU_RECORDING=true \
     - OPENVIDU_RECORDING_PATH=/Users/rishurai/Desktop/VideoChatApp/recordings \
    volumes:
      - /var/run/docker.sock: /var/run/docker.sock \
      - /Users/rishurai/Desktop/VideoChatApp/recordings: /Users/rishurai/Desktop/VideoChatApp/recordings \
    

 